name: Démonstration Pipeline CI

on:
    push:
        branches: [ "main"]

jobs:
    demo:
        name: Demo son nom
        runs-on: ubuntu-latest

        steps:
            - name: Première étape
              run: echo Hello !