name: Démonstration Pipeline CI

on:
    push:
        branches: [ "main"]

jobs:
    demo:
        name: Demo son nom
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [8.1, 8.2, 8.3]

        steps:
            - name: Première étape - ${{ matrix.php }}
              run: echo Hello ! 

            - name: Script plus complexe
              run: |
                echo Voici
                echo un script plus compliqué
        
    test:
        needs: demo
        runs-on: ubuntu-latest

        steps:
            - name: Récupération code source
              uses: actions/checkout@v4

            - name: Etape 2
              run: echo "L'Étape 2"